(async () => {
  const results = [];
  const check = (condition, message) => { if (!condition) throw new Error(message); results.push(message); };
  const manager = new WindowManager();
  const win = new FMWindow(manager, { path: '/test', x: 20, y: 20, width: 1200, height: 400 });
  manager.windows.push(win);
  win.viewMode = 'detail';
  const folder = { id: '/test/folder', path: '/test/folder', name: 'folder', kind: 'directory', color: '#aaa', size: 0 };
  win.entries = [folder];
  await FileView.render(win);
  const table = win.el.querySelector('.detail-table');
  const headers = [...table.querySelectorAll('th')];
  const before = headers.map(h => h.getBoundingClientRect());
  const x = before[1].right - 2;
  headers[1].querySelector('.col-resize-handle').dispatchEvent(new MouseEvent('mousedown', { button: 0, clientX: x, bubbles: true }));
  window.dispatchEvent(new MouseEvent('mousemove', { clientX: x + 85 }));
  window.dispatchEvent(new MouseEvent('mouseup'));
  const after = headers.map(h => h.getBoundingClientRect());
  check(Math.abs(after[1].right - before[1].right - 85) < 1, 'Column boundary follows pointer by exactly the drag distance in a wide window');
  check(before.every((rect, i) => i === 1 || Math.abs(rect.width - after[i].width) < 1), 'Dragging preserves all other column widths');
  win.el.style.width = '400px';
  const content = win.el.querySelector('.fm-content');
  content.scrollLeft = 100;
  const last = headers.at(-1), edge = last.getBoundingClientRect().right;
  last.querySelector('.col-resize-handle').dispatchEvent(new MouseEvent('mousedown', { button: 0, clientX: edge - 2, bubbles: true }));
  window.dispatchEvent(new MouseEvent('mousemove', { clientX: edge - 42 }));
  window.dispatchEvent(new MouseEvent('mouseup'));
  check(Math.abs(last.getBoundingClientRect().right - edge + 40) < 1, 'Last column shrinks correctly in a horizontally scrolled view');
  const scroll = content.scrollLeft;
  window.fm.calculateFolderSize = async () => ({ bytes: 4321, files: 3, skipped: 1, links: 0, calculatedAt: Date.now() });
  await FileView.calculateFolderSize(win, folder);
  check(win.el.querySelector('.cell-size').textContent.includes('partial'), 'Calculated partial totals appear in existing Size cells');
  check(content.scrollLeft === scroll && win.el.querySelector('.detail-table') === table, 'Calculating size preserves the viewport and existing table');
  check(win.el.querySelector('.cell-size').title.includes('4,321'), 'Saved size tooltip includes exact bytes and calculation date');
  await FileView.render(win);
  check(win.el.querySelector('.cell-size').textContent.includes('partial'), 'Calculated size survives rendering again');
  const original = ContextMenu.showAt;
  let items;
  ContextMenu.showAt = value => { items = value; };
  ContextMenu.showForEntry(win, folder, 0, 0);
  check(items.some(item => item.label === 'Calc Folder Size'), 'Detail folder context menu includes Calc Folder Size');
  win.viewMode = 'icon';
  ContextMenu.showForEntry(win, folder, 0, 0);
  check(!items.some(item => item.label === 'Calc Folder Size'), 'Folder size command is limited to detail view');
  ContextMenu.showAt = original;
  manager.close(win.id);
  return results;
})();
