(async () => {
  const results = [];
  const check = (value, message) => { if (!value) throw new Error(message); results.push(message); };
  const manager = new WindowManager();
  const win = new FMWindow(manager, { path: '/photos', x: 20, y: 20, width: 600, height: 420 });
  manager.windows.push(win); manager.focus(win.id);
  initKeyboardShortcuts(manager);
  const entry = { id: 'real', path: '/photos/picture.png', name: 'picture.png', kind: 'image', isVirtual: true, color: '#fff', dataUrl: 'data:image/svg+xml,' + encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><rect width="32" height="32" fill="red"/></svg>') };
  win.entries = [entry, { ...entry, id: 'second', name: 'second.png' }];
  win.selection = new Set([entry.id]);
  await FileView.render(win);
  document.activeElement?.blur();
  const requests = [];
  window.fm.showFileProperties = async p => requests.push(p);
  const key = new KeyboardEvent('keydown', { key: 'Enter', altKey: true, bubbles: true, cancelable: true });
  document.dispatchEvent(key);
  check(key.defaultPrevented && requests[0] === entry.path && !win.preview, 'Alt+Enter opens native Properties for real-backed virtual entries without opening the viewer');
  const original = ContextMenu.showAt;
  let items;
  ContextMenu.showAt = value => { items = value; };
  ContextMenu.showForEntry(win, entry, 0, 0);
  check(!items.some(item => item.label?.includes('Generated')), 'Virtual entry menu no longer contains Generated — read only');
  items.find(item => item.label === 'Properties').action();
  check(requests.length === 2, 'Properties context command targets the same real file');
  ContextMenu.showForEntry(win, { ...entry, path: 'vdir://generated' }, 0, 0);
  check(items.find(item => item.label === 'Properties').disabled, 'Synthetic entries cannot invoke OS file properties');
  ContextMenu.showAt = original;
  const icon = win.el.querySelector('[data-entry-id="real"]');
  const parent = icon.parentElement;
  const observer = new MutationObserver(() => {});
  observer.observe(parent, { childList: true });
  icon.dispatchEvent(new MouseEvent('mousedown', { button: 0, bubbles: true }));
  const mutations = observer.takeRecords(); observer.disconnect();
  check(!mutations.some(record => [...record.removedNodes].includes(icon)), 'Raising an image never detaches the pressed double-click target');
  check(parent.lastElementChild === icon, 'Image still raises above other icons');
  // Start behind another icon so real input exercises raising during the click.
  parent.appendChild(parent.querySelector('[data-entry-id="second"]'));
  window.__imageClickTest = { win, manager };
  await new Promise(resolve => setTimeout(resolve, 200));
  const rect = icon.querySelector('.icon-square').getBoundingClientRect();
  return { results, x: Math.round(rect.left + 10), y: Math.round(rect.top + 10) };
})();
