(async () => {
  const results = [];
  const check = (condition, message) => { if (!condition) throw new Error(message); results.push(message); };
  AppSettings.current = { ...APP_SETTINGS_DEFAULTS }; AppSettings.apply(AppSettings.current);
  const manager = new WindowManager(); WindowSystemMenu.manager = manager;
  const owner = new FMWindow(manager, { path: '/photos', x: 20, y: 20, width: 500, height: 400 });
  manager.windows.push(owner); manager.focus(owner.id);
  const local = { name: 'my-photo.txt', id: '/photos/my-photo.txt', path: '/photos/my-photo.txt', kind: 'file', color: '#aaa', ext: '.txt', isVirtual: false, size: 10, modified: Date.now(), created: Date.now(), parentDirectory: '/photos' };
  const child = { ...local, id: '/photos/child/my-photo.txt', path: '/photos/child/my-photo.txt', parentDirectory: '/photos/child' };
  owner.entries = [local, { ...local, name: 'other.txt', id: '/photos/other.txt', path: '/photos/other.txt' }];
  await FileView.render(owner);
  const requests = [];
  const cancelled = [];
  window.fm.onSearchProgress=()=>()=>{};
  window.fm.cancelSearch = id => cancelled.push(id);
  window.fm.searchDirectory = async request => { requests.push(request); return { entries: request.recursive ? [local, child] : [local], skipped: 0, truncated: false }; };
  owner.el.querySelector('.fm-search-btn').click();
  const gui = owner.searchDialog;
  gui.query.value = 'previous query';
  manager.focus(owner.id);
  owner.el.querySelector('.fm-location-input').focus();
  const findKey = new KeyboardEvent('keydown', { key: 'f', ctrlKey: true, cancelable: true });
  check(FolderSearch.shortcut(findKey, manager) && findKey.defaultPrevented && document.activeElement === gui.query, 'Ctrl+F opens source folder search even from the address bar');
  check(gui.query.selectionStart === 0 && gui.query.selectionEnd === gui.query.value.length, 'Search shortcut selects the existing query');
  const searchKey = new KeyboardEvent('keydown', { key: 'e', ctrlKey: true, cancelable: true });
  check(FolderSearch.shortcut(searchKey, manager) && owner.searchDialog === gui, 'Ctrl+E reuses the same linked search GUI');
  check(gui?.owner === owner && gui.type === 'search', 'S opens a search GUI tied to its source folder');
  owner.el.querySelector('.fm-search-btn').click();
  check(owner.searchDialog === gui && manager.windows.length === 2, 'Repeated S focuses the existing folder search GUI');
  gui.query.value = 'photo';
  gui.el.querySelector('.search-select').checked = true;
  gui.el.querySelector('.search-highlight-option').checked = true;
  gui.el.querySelector('.search-recursive').checked = true;
  await gui.search();
  check(requests[0].recursive && requests[0].root === '/photos', 'Recursive search receives the originating directory');
  check(owner.selection.size === 1 && owner.selection.has(local.id), 'Select applies only matches present in the originating folder');
  check(owner.searchHighlights.size === 1 && owner.el.querySelector('.search-highlight'), 'Highlight marks only the originating folder matches');
  check(getComputedStyle(owner.el.querySelector('.search-highlight .icon-square')).outlineColor === 'rgb(0, 255, 255)', 'Search highlight defaults to an aqua border');
  check(manager.windows.length === 2, 'Select/Highlight do not open a separate results window');
  await FileView.render(owner);
  check(!!owner.el.querySelector('.search-highlight'), 'Highlights survive icon rerendering');
  owner.viewMode = 'detail'; await FileView.render(owner);
  check(!!owner.el.querySelector('.detail-row.search-highlight'), 'Highlights also appear in detail view');
  AppSettings.apply({ ...APP_SETTINGS_DEFAULTS, searchHighlightColor: '#ff00ff' });
  check(getComputedStyle(owner.el.querySelector('.detail-row.search-highlight td')).borderTopColor === 'rgb(255, 0, 255)', 'Settings updates existing search highlight borders live');
  gui.el.querySelector('.search-select').checked = false;
  gui.el.querySelector('.search-highlight-option').checked = false;
  await gui.search();
  const resultWin = manager.windows.find(win => win.type === 'search-results');
  const columns = [...resultWin.el.querySelectorAll('.col-label')].map(el => el.textContent);
  check(columns.length === FileView.DETAIL_COLUMNS.length + 1 && columns[1] === 'Parent Directory', 'Results detail view adds Parent Directory as the second column');
  check(resultWin.entries.length === 2 && resultWin.el.querySelectorAll('tbody tr')[1].children[1].textContent === '/photos/child', 'Results retain matching files from different parent folders');
  check(owner.searchHighlights.size === 0, 'Searching with Highlight unchecked clears prior search borders');
  gui.el.querySelector('.search-recursive').checked = false;
  await gui.search();
  check(requests.at(-1).recursive === false, 'Unchecked recursion searches only the source directory');
  let complete;
  window.fm.searchDirectory = () => new Promise(resolve => { complete = resolve; });
  const pending = gui.search();
  await new Promise(resolve=>setTimeout(resolve,0));
  gui.cancel();
  const count = manager.windows.length;
  complete({ entries: [local], skipped: 0, truncated: false });
  await pending;
  check(cancelled.length === 1 && manager.windows.length === count, 'Stopping search suppresses late results');
  const next = gui.search();
  await new Promise(resolve=>setTimeout(resolve,0));
  window.fm.listDir = async path => ({ path, entries: [], canGoUp: true });
  await owner.navigate('/elsewhere');
  complete({ entries: [local], skipped: 0, truncated: false });
  await next;
  check(owner.searchHighlights.size === 0 && gui.el.querySelector('.search-scope').textContent.includes('/elsewhere'), 'Navigation cancels stale searches and updates the linked search scope');
  manager.close(owner.id);
  check(!gui.el.isConnected && !owner.el.isConnected, 'Closing a source folder closes its linked search GUI');
  for (const win of [...manager.windows]) manager.close(win.id);
  return results;
})()
