(async () => {
  const results = [];
  const check = (condition, message) => {
    if (!condition) throw new Error(message);
    results.push(message);
  };
  const pause = (ms) => new Promise(resolve => setTimeout(resolve, ms));
  const saved = [];
  window.fm = {
    recordOpened:async()=>{}, getLayout: async () => ({}), setLayoutPos: async (...args) => saved.push(args), toFileUrl: p => p };
  const source = document.createElement('canvas');
  source.width = 2; source.height = 2;
  const ctx = source.getContext('2d');
  ctx.fillStyle = '#000'; ctx.fillRect(0, 0, 2, 2);
  ctx.fillStyle = '#fff'; ctx.fillRect(1, 0, 1, 2);
  const url = source.toDataURL();
  const entries = [
    { id: 'a', name: 'first.png', kind: 'image', dataUrl: url, color: '#fff', isVirtual: true },
    { id: 'b', name: 'second.png', kind: 'image', dataUrl: url, color: '#fff', isVirtual: true },
    { id: 'c', name: 'notes.txt', kind: 'file', color: '#a00', isVirtual: true },
  ];
  const win = { el: document.querySelector('#desktop'), path: 'vdir://test', entries,
    selection: new Set(), sortKey: 'name', sortDir: 1, viewMode: 'icon',
    manager: { focus() {} }, setStatus() {} };
  const content = document.querySelector('.fm-content');
  await FileView.renderIconView(win, content);
  const a = content.querySelector('[data-entry-id="a"]');
  const b = content.querySelector('[data-entry-id="b"]');
  const file = content.querySelector('[data-entry-id="c"]');
  await pause(300);
  check(a.querySelector('img').naturalWidth === 2, 'Image thumbnails decode');
  check(!file.querySelector('img'), 'Non-image icons keep their colored square');
  const originalX = a.style.left;
  a.dispatchEvent(new WheelEvent('wheel', { ctrlKey: true, deltaY: -120, bubbles: true, cancelable: true }));
  await pause(200);
  const bigger = parseFloat(a.style.getPropertyValue('--icon-size'));
  check(bigger > 30 && a.style.left === originalX, 'Ctrl+wheel grows only the hovered icon without moving it');
  check(!b.style.getPropertyValue('--icon-size'), 'Neighbor size is unchanged');
  a.dispatchEvent(new WheelEvent('wheel', { ctrlKey: true, deltaY: 120, cancelable: true }));
  await pause(200);
  check(Math.abs(parseFloat(a.style.getPropertyValue('--icon-size')) - 30) < 0.01, 'Wheel-down reverses wheel-up');
  check(IconAppearance.sizeAfterWheel(3840, -100, 0) === 3840 && IconAppearance.sizeAfterWheel(16, 100, 0) === 16, 'Size bounds apply');
  check(IconAppearance.sizeAfterWheel(30, -1, 1) === IconAppearance.sizeAfterWheel(30, -16, 0), 'Line and pixel wheel units agree');
  a.dispatchEvent(new MouseEvent('mousedown', { button: 0, bubbles: true }));
  check(a.parentElement.lastElementChild === a && win.selection.has('a'), 'Click raises and selects the image');
  a.dispatchEvent(new MouseEvent('click', { altKey: true, bubbles: true }));
  await pause(200);
  check(!a.querySelector('canvas').hidden, 'Alt+click renders a bilinear thumbnail after raising the icon');
  const output = document.createElement('canvas');
  BilinearThumbnails.draw(a.querySelector('img'), output, 16, 16);
  const pixels = output.getContext('2d').getImageData(0, 0, output.width, output.height).data;
  const center = pixels[(Math.floor(output.height / 2) * output.width + Math.floor(output.width / 2)) * 4];
  check(center > 80 && center < 190, 'Bilinear interpolation blends neighboring texels');
  let opened = false;
  const originalOpenEntry = FileView.openEntry;
  FileView.openEntry = () => { opened = true; };
  a.dispatchEvent(new MouseEvent('dblclick', { altKey: true, bubbles: true }));
  check(!opened, 'Alt+double-click does not open the image viewer');
  a.dispatchEvent(new MouseEvent('dblclick', { bubbles: true }));
  check(opened, 'Ordinary double-click still opens images');
  FileView.openEntry = originalOpenEntry;
  check(saved.some(([, , patch]) => patch.scaling === 'bilinear') && saved.some(([, , patch]) => patch.size > 30), 'Appearance patches reach persistence');
  content.innerHTML = '';
  win.layout['a'] = { size: 100, scaling: 'bilinear' };
  await FileView.renderIconView(win, content);
  await pause(200);
  const restored = content.querySelector('[data-entry-id="a"]');
  check(parseFloat(restored.style.getPropertyValue('--icon-size')) === 100 && !restored.querySelector('canvas').hidden, 'Saved appearance restores without requiring a saved position');
  const bad = document.createElement('div');
  bad.className = 'icon-item'; bad.innerHTML = '<div class="icon-square"></div>';
  content.append(bad);
  IconAppearance.attach(bad, { name: 'broken.png', kind: 'image', dataUrl: 'data:image/png;base64,bad' }, {}, () => {});
  await pause(200);
  check(bad.querySelector('img').hidden && !bad.querySelector('.has-thumbnail'), 'Broken images fall back to a colored icon');
  DesktopShortcuts.appearances = {};
  const shortcut = DesktopShortcuts.renderOne({ id: 'test', name: 'shortcut.png', kind: 'image', targetPath: url, color: '#aaa', x: 500, y: 100 });
  await pause(200);
  shortcut.dispatchEvent(new WheelEvent('wheel', { ctrlKey: true, deltaY: -100, cancelable: true }));
  shortcut.dispatchEvent(new MouseEvent('click', { altKey: true }));
  await pause(200);
  check(parseFloat(shortcut.style.getPropertyValue('--icon-size')) > 30 && !shortcut.querySelector('canvas').hidden, 'Desktop shortcuts share resize and bilinear controls');
  check(getComputedStyle(shortcut).zIndex === '1', 'Desktop images remain below application windows');
  shortcut.remove();
  content.innerHTML = '';
  await pause(200);
  check(IconAppearance.live.size === 0, 'Removed views release thumbnail observers');
  for (const [name, width, height] of [['portrait', 100, 400], ['landscape', 400, 100]]) {
    const icon = document.createElement('div');
    icon.className = 'icon-item';
    icon.style.left = '0px'; icon.style.top = '20px';
    icon.innerHTML = '<div class="icon-square"></div><div class="icon-label"><span class="icon-label-text">Photo.png</span></div>';
    content.append(icon);
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><rect width="100%" height="100%" fill="coral"/></svg>`;
    IconAppearance.attach(icon, { name: `${name}.svg`, kind: 'image', dataUrl: `data:image/svg+xml;base64,${btoa(svg)}` }, { size: 240 }, () => {});
    await pause(250);
    const bounds = icon.getBoundingClientRect();
    const frame = icon.querySelector('.icon-square').getBoundingClientRect();
    check(Math.abs(bounds.width / bounds.height - width / height) < 0.01, `${name}: icon bounds follow image aspect ratio`);
    check(frame.left === bounds.left && frame.top === bounds.top && frame.width === bounds.width && frame.height === bounds.height, `${name}: image hit area has no inset or square padding`);
    check(document.elementFromPoint(frame.left + 10, frame.top + 10)?.closest('.icon-item') === icon, `${name}: image surface remains clickable`);
    const outsideX = frame.left + (width < height ? frame.width + 20 : 20);
    const outsideY = frame.top + (width < height ? 20 : frame.height + 20);
    check(document.elementFromPoint(outsideX, outsideY)?.closest('.icon-item') !== icon, `${name}: former square padding lets clicks through`);
    icon.dispatchEvent(new MouseEvent('click', { altKey: true }));
    await pause(150);
    check(!icon.querySelector('canvas').hidden && icon.querySelector('canvas').clientWidth === icon.querySelector('.icon-square').clientWidth, `${name}: bilinear thumbnail uses the same image bounds`);
    icon.remove();
  }
  await pause(150);
  let profile;
  let refreshes = 0;
  window.fm.getAppSettings = async () => ({ iconSize: 30 });
  window.fm.setAppSettings = async value => { profile = { ...value }; };
  await AppSettings.init({ refreshAllDirectoryWindows() { refreshes++; } });
  AppSettings.open();
  const color = AppSettings.el.querySelector('.app-label-color');
  const opacity = AppSettings.el.querySelector('.app-label-opacity');
  const size = AppSettings.el.querySelector('.app-icon-size');
  check(color.value === '#ffffff' && opacity.value === '88', 'Older settings receive original label defaults');
  color.value = '#ff8000'; opacity.value = '25';
  AppSettings.el.querySelector('.app-native-icons').checked = true;
  AppSettings.el.querySelector('.app-search-highlight-color').value = '#ff00ff';
  opacity.dispatchEvent(new Event('input'));
  check(getComputedStyle(AppSettings.el.querySelector('.icon-label-text')).backgroundColor === 'rgba(255, 128, 0, 0.25)', 'Label preview shows color and alpha together');
  await AppSettings.save();
  check(profile.labelBackgroundColor === '#ff8000' && profile.labelBackgroundAlpha === 0.25, 'Label appearance saves to the app settings profile');
  check(profile.searchHighlightColor === '#ff00ff', 'Search highlight color saves to the app settings profile');
  check(profile.useNativeIcons === true && NativeFileIcons.enabled, 'Native icon preference saves and applies');
  check(refreshes === 0, 'Label-only changes do not refresh folders or reset their viewport');
  AppSettings.open();
  check(color.value === '#ff8000' && opacity.value === '25', 'Label controls restore saved values');
  opacity.value = '0';
  await AppSettings.save();
  check(profile.labelBackgroundAlpha === 0, 'Fully transparent labels are supported');
  AppSettings.open();
  size.value = '3840';
  await AppSettings.save();
  check(profile.iconSize === 3840 && refreshes === 1, 'Settings accepts a default icon size of 3840 pixels');
  AppSettings.open();
  AppSettings.el.querySelector('.term-reset-btn').click();
  check(size.value === '30' && color.value === '#ffffff' && opacity.value === '88', 'Reset restores original icon and label defaults');
  AppSettings.close();
  check(AppSettings.current.iconSize === 3840 && AppSettings.current.labelBackgroundAlpha === 0, 'Cancel leaves saved settings unchanged');
  return results;
})()
