(async () => {
  const results = [];
  const check = (ok, message) => { if (!ok) throw new Error(message); results.push(message); };
  const pause = () => new Promise(resolve => setTimeout(resolve, 10));
  const manager = new WindowManager();
  const win = new FMWindow(manager, { path: '/files', x: 20, y: 20, width: 700, height: 400 });
  manager.windows.push(win); manager.focus(win.id);
  win.viewMode = 'detail';
  const entry = { id: 'a', name: 'a.txt', path: '/files/a.txt', kind: 'file', color: '#aaa', order: 'A10', ext: '.txt' };
  const folder = { ...entry, id: 'b', name: 'folder', path: '/files/folder', kind: 'directory', order: 'A2' };
  win.entries = [entry, folder, { ...entry, id: 'c', path: '/files/c.txt', order: 'A2' }];
  await FileView.render(win);
  for (const label of ['PrevName', 'OrigName', 'MD5', 'SHA256', 'SHA512', '#', 'Note']) {
    check([...win.el.querySelectorAll('.col-label')].some(el => el.textContent === label), `Detail view includes ${label}`);
  }
  win.sortKey = 'order'; win.sortDir = 1;
  check(FileView.sortedEntries(win).map(e => e.id).join() === 'b,c,a', '# sorts alphanumeric values naturally and retains duplicate values');
  win.sortDir = -1;
  check(FileView.sortedEntries(win)[0].id === 'a', '# supports descending sort');
  const saved = [];
  window.fm.editEntryMetadata = async (path, field, value) => { saved.push({ path, field, value }); return { [field]: value }; };
  const cell = win.el.querySelector('[data-entry-id="a"] .cell-note');
  cell.click();
  const input = cell.querySelector('input'); input.value = 'My note';
  input.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true }));
  await pause();
  check(saved[0].value === 'My note' && cell.textContent === 'My note', 'Click-to-edit Note saves with Enter');
  cell.click(); cell.querySelector('input').value = 'discard';
  cell.querySelector('input').dispatchEvent(new KeyboardEvent('keydown', { key: 'Escape', bubbles: true }));
  await pause();
  check(cell.textContent === 'My note' && saved.length === 1, 'Escape cancels an edit without saving');
  await FileView.favorite(win, entry);
  check(entry.bookmarked && win.el.querySelector('[data-entry-id="a"]').classList.contains('favorite-highlight'), 'Favorite immediately highlights the item');
  AppSettings.apply({ ...APP_SETTINGS_DEFAULTS, favoriteHighlightColor: '#ff00ff' });
  check(getComputedStyle(cell).boxShadow.includes('255, 0, 255'), 'Favorite border has its own configurable color');
  let items; const show = ContextMenu.showAt; ContextMenu.showAt = value => { items = value; };
  AppSettings.current.showHashCalc = true; ContextMenu.showForEntry(win, entry, 0, 0);
  check(['MD5', 'SHA256', 'SHA512'].every(a => items.some(i => i.label === `Calculate ${a}`)), 'Hash calculations are available on demand');
  AppSettings.current.showHashCalc = false; ContextMenu.showForEntry(win, entry, 0, 0);
  check(!items.some(i => i.label?.startsWith('Calculate ')), 'Settings checkbox hides hash commands');
  AppSettings.current.showHashCalc = true; ContextMenu.showAt = show;
  const requests = []; window.fm.copyItem = async (...args) => { requests.push(args); return {}; };
  win.selection = new Set(['a', 'b']); Clipboard.copy(win);
  const destination = { path: '/destination', navigate: async () => {}, manager, setStatus() {} };
  await Clipboard.paste(destination);
  check(requests.length === 2 && requests.some(([p]) => p === folder.path), 'Clipboard copies mixed files and folders in a multiple selection');
  const row = win.el.querySelector('[data-entry-id="a"]');
  row.dispatchEvent(new MouseEvent('mousedown', { ctrlKey: true, button: 0, bubbles: true }));
  const data = new Map();
  const drag = new Event('dragstart', { bubbles: true });
  Object.defineProperty(drag, 'dataTransfer', { value: { setData: (k, v) => data.set(k, v) } });
  row.dispatchEvent(drag);
  check(JSON.parse(data.get('application/x-fm-paths')).paths.length === 2, 'Ctrl-drag retains the entire selected group');
  manager.close(win.id);
  AppSettings.apply(APP_SETTINGS_DEFAULTS);
  return results;
})();
