(async () => {
  const results = [];
  const check = (condition, message) => { if (!condition) throw new Error(message); results.push(message); };
  const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
  const calls = [];
  window.fm.platform = window.__nativePlatform;
  window.fm.getFileIconFamily = async (file, revision) => { calls.push({ file, revision }); return file.endsWith('missing') ? [] : window.__nativeTestFamily; };
  const create = (file, x = 100, y = 100) => {
    const square = document.createElement('div');
    square.className = 'mini-square';
    square.style.cssText = `position:absolute;left:${x}px;top:${y}px;width:16px;height:16px;background:red`;
    document.body.append(square);
    NativeFileIcons.attach(square, { path: file, modified: 1 });
    return square;
  };
  NativeFileIcons.setEnabled(false);
  const square = create(window.__nativeTestPath);
  await pause(100);
  check(calls.length === 0, 'Color-block mode makes no native-icon requests');
  NativeFileIcons.setEnabled(true);
  await pause(200);
  check(square.classList.contains('has-native-icon') && square.querySelector('img').naturalWidth > 0, 'A real Windows OS icon decodes and displays');
  check(square.clientWidth === 16 && calls.length === 1, 'One request preloads the full native size family');
  const same = create(window.__nativeTestPath, 130);
  await pause(150);
  check(calls.length === 1 && same.classList.contains('has-native-icon'), 'Repeated file icons share a cached request');
  square.style.width = square.style.height = '32px';
  await pause(150);
  check(calls.length === 1, 'Resizing to 32 pixels uses cached artwork without another lookup');
  square.style.width = square.style.height = '200px';
  await pause(150);
  check(calls.length === 1 && square.querySelector('img').naturalWidth >= 256, 'Enlarging selects cached high-resolution artwork without another lookup');
  const alphaCanvas = document.createElement('canvas'); alphaCanvas.width = alphaCanvas.height = 256;
  const alphaContext = alphaCanvas.getContext('2d');
  alphaContext.drawImage(square.querySelector('img'), 0, 0, 256, 256);
  const rgba = alphaContext.getImageData(0, 0, 256, 256).data;
  check(rgba.some((value, index) => index % 4 === 3 && value === 0) && rgba.some((value, index) => index % 4 === 3 && value > 0), 'High-resolution Windows icon retains transparent and visible pixels');
  NativeFileIcons.setEnabled(false);
  check(!square.classList.contains('has-native-icon') && square.querySelector('img').hidden, 'Turning native icons off restores color blocks in place');
  NativeFileIcons.setEnabled(true);
  const broken = create(window.__nativeTestPath + '-missing', 180);
  const offscreen = create(window.__nativeTestPath + '-offscreen', 220, 5000);
  await pause(150);
  check(!broken.classList.contains('has-native-icon'), 'Unavailable OS icons retain their colored fallback');
  check(calls.some(call => call.file.endsWith('-offscreen')), 'Listed offscreen icons also preload their full resolution family');
  offscreen.style.top = '100px';
  await pause(150);
  check(offscreen.classList.contains('has-native-icon'), 'Icons load when scrolled into view');
  const folder = document.createElement('div');
  folder.className = 'icon-item'; folder.style.cssText = 'left:300px;top:100px';
  folder.innerHTML = '<div class="icon-square"></div><div class="icon-label"><span class="icon-label-text">Folder</span></div>';
  document.body.append(folder);
  const beforeFolder = calls.length;
  IconAppearance.attach(folder, { kind: 'directory', path: 'vdir://folder', name: 'Folder' }, { size: 32 }, () => {});
  await pause(150);
  check(folder.querySelector('.os-file-icon').naturalWidth === 32 && folder.querySelector('.os-file-icon').src.endsWith('/assets/folder.svg'), 'Folders use the supplied SVG, including virtual folders');
  check(calls.length === beforeFolder, 'Folder SVG rendering never requests an OS folder icon');
  for (let index = 0; index < 30; index++) folder.dispatchEvent(new WheelEvent('wheel', { ctrlKey: true, deltaY: 240, cancelable: true }));
  await pause(150);
  check(parseFloat(folder.style.getPropertyValue('--icon-size')) === 16 && folder.querySelector('.icon-square').clientWidth === 16, 'Repeated Ctrl+wheel-down stops at 16 pixels (100% of a 16x16 icon)');
  folder.remove();
  square.remove(); same.remove(); broken.remove(); offscreen.remove();
  await pause(150);
  check(NativeFileIcons.controllers.size === 0, 'Removed native icons release their observers');
  NativeFileIcons.setEnabled(false);
  return results;
})()
