(async () => {
  const results = [];
  const check = (ok, message) => { if (!ok) throw new Error(message); results.push(message); };
  const manager = new WindowManager();
  const win = new FMWindow(manager, { path: '/test', x: 15, y: 15, width: 650, height: 420 });
  manager.windows.push(win); manager.focus(win.id); initKeyboardShortcuts(manager);
  win.viewMode = 'detail';
  const entry = { id: 'rename', path: '/test/old.txt', name: 'old.txt', kind: 'file', color: '#aaa' };
  win.entries = [entry]; win.selection = new Set([entry.id]);
  await FileView.render(win);
  let opened = 0, renamed = 0;
  const originalOpen = FileView.openEntry, originalRename = window.fm.renameItem;
  FileView.openEntry = () => { opened++; };
  window.fm.renameItem = async (p, name) => { check(p === entry.path && name === 'new.txt', 'Rename receives the new name'); renamed++; };
  win.navigate = async () => {};
  FileView.startRename(win, entry);
  const rename = win.el.querySelector('.rename-input'); rename.value = 'new.txt';
  const enter = new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true });
  rename.dispatchEvent(enter);
  await Promise.resolve();
  check(enter.defaultPrevented && renamed === 1 && opened === 0, 'Enter finalizes rename without reaching the file-open shortcut');
  FileView.openEntry = originalOpen; window.fm.renameItem = originalRename;

  AppSettings.current = { ...APP_SETTINGS_DEFAULTS }; AppSettings.apply(AppSettings.current); AppSettings.open();
  const defaultBorder = getComputedStyle(win.el).borderTopWidth;
  const box = AppSettings.el.querySelector('.app-settings-box');
  const first = AppSettings.el.querySelector('.settings-general').getBoundingClientRect();
  const second = AppSettings.el.querySelector('.settings-appearance').getBoundingClientRect();
  check(first.width > 200 && second.width > 250 && first.right <= second.left + 1 && second.right <= innerWidth, 'Both settings columns are visible side by side');
  check(!AppSettings.el.querySelector('.modal-title') && AppSettings.el.querySelector('.settings-titlebar').textContent.includes('Settings'), 'Settings uses a titlebar without the old duplicate heading');
  check(AppSettings.el.querySelectorAll('[data-window-setting]').length === WindowAppearance.fields.length, 'Every window appearance variable has a labeled control');
  const change = (key, value) => {
    const input = AppSettings.el.querySelector(`[data-window-setting="${key}"]`);
    input.value = value; input.dispatchEvent(new Event('input', { bubbles: true }));
  };
  change('frame', '#334455'); change('border-width', 4); change('title-height', 36);
  check(getComputedStyle(win.el).backgroundColor === 'rgb(51, 68, 85)' && getComputedStyle(win.el).borderTopWidth === '4px', 'Frame color and border width preview live');
  check(win.el.querySelector('.fm-titlebar').getBoundingClientRect().height === 36, 'Titlebar height changes live');
  AppSettings.el.querySelector('.app-icon-size').value = '48';
  AppSettings.el.querySelector('.window-defaults-btn').click();
  check(AppSettings.el.querySelector('.app-icon-size').value === '48' && getComputedStyle(win.el).borderTopWidth === defaultBorder, 'Window Defaults resets only the second section');
  change('frame', '#445566'); AppSettings.close();
  check(getComputedStyle(win.el).backgroundColor === 'rgb(192, 192, 192)', 'Cancel discards the live appearance preview');
  AppSettings.open(); change('frame', '#556677');
  let persisted;
  window.fm.setAppSettings = async settings => { persisted = settings; };
  await AppSettings.save();
  check(persisted.windowAppearance.frame === '#556677', 'Saving persists the complete appearance section');
  AppSettings.open();
  check(AppSettings.el.querySelector('[data-window-setting="frame"]').value === '#556677', 'Reopening Settings restores saved appearance values');
  const title = AppSettings.el.querySelector('.settings-titlebar'), before = box.getBoundingClientRect();
  title.dispatchEvent(new PointerEvent('pointerdown', { button: 0, pointerId: 1, clientX: before.left + 20, clientY: before.top + 10, bubbles: true }));
  window.dispatchEvent(new PointerEvent('pointermove', { pointerId: 1, clientX: before.left + 50, clientY: before.top + 25 }));
  window.dispatchEvent(new PointerEvent('pointerup', { pointerId: 1 }));
  const after = box.getBoundingClientRect();
  check(Math.abs(after.left - before.left - 30) < 1 && Math.abs(after.top - before.top - 15) < 1, 'Dragging the Settings titlebar moves the entire dialog');
  const context = document.createElement('div'); context.className = 'context-menu';
  context.innerHTML = '<div class="ctx-item">Example</div>'; document.body.appendChild(context);
  check(getComputedStyle(context.firstChild).paddingTop === '2px', 'Context-menu rows have reduced vertical padding by default'); context.remove();
  AppSettings.el.querySelector('.window-defaults-btn').click();
  await AppSettings.save(); AppSettings.open();
  manager.close(win.id);
  return results;
})();
