(async () => {
  const results = [];
  const check = (condition, message) => { if (!condition) throw new Error(message); results.push(message); };
  ContextMenu.hide = () => {};
  const manager = new WindowManager();
  let nativeCommand;
  window.fm.onWindowSystemCommand = callback => { nativeCommand = callback; };
  WindowSystemMenu.init(manager);
  const win = new FMWindow(manager, { path: '/photos', x: 100, y: 80, width: 500, height: 400 });
  manager.windows.push(win); manager.focus(win.id);
  const key = (key, options = {}) => window.dispatchEvent(new KeyboardEvent('keydown', { key, bubbles: true, cancelable: true, ...options }));
  const menu = () => key('q', { code: 'KeyQ', altKey: true });
  key(' ', { code: 'Space', altKey: true });
  check(!WindowSystemMenu.menu, 'Alt+Space no longer opens the internal menu');
  key('e', { code: 'KeyE', altKey: true });
  check(!WindowSystemMenu.menu, 'Alt+E is reserved for Home and no longer opens the internal menu');
  key('Escape');
  const platform = window.fm.platform;
  window.fm.platform = 'darwin';
  key(' ', { code: 'Space', metaKey: true });
  check(!!WindowSystemMenu.menu, 'Command+Space opens the internal menu on macOS');
  key('Escape'); window.fm.platform = platform;
  let bubbled = 0;
  const onKey = () => bubbled++;
  window.addEventListener('keydown', onKey);
  menu();
  check(WindowSystemMenu.menu?.querySelectorAll('[role=menuitem]').length === 6, 'Alt+Q opens all six system-menu commands');
  const osShortcut = new KeyboardEvent('keydown', { key: ' ', code: 'Space', altKey: true, cancelable: true });
  window.dispatchEvent(osShortcut);
  check(!osShortcut.defaultPrevented && !!WindowSystemMenu.menu, 'Alt+Space is not consumed even while the internal menu is open');
  bubbled = 0; // Alt+Space deliberately passes through; internal commands below must not.
  key('m'); key('ArrowRight'); key('ArrowDown', { ctrlKey: true });
  check(win.x === 108 && win.y === 81, 'Move supports arrow keys and Ctrl+arrow fine positioning');
  key('Escape');
  check(win.x === 100 && win.y === 80 && !WindowSystemMenu.operation, 'Escape cancels Move and restores exact bounds');
  menu(); key('m'); key('ArrowLeft'); key('Enter');
  check(win.x === 92 && !WindowSystemMenu.operation, 'Enter commits Move');
  menu(); key('s'); key('ArrowLeft');
  check(win.width === 500 && win.x === 92, 'Size first arrow selects the edge without changing geometry');
  key('ArrowLeft');
  check(win.width === 508 && win.x === 84, 'Sizing the left edge keeps the right edge fixed');
  key('ArrowUp'); key('ArrowUp', { ctrlKey: true });
  check(win.y === 79 && win.height === 401, 'Size can select a corner and resize both axes');
  key('Escape');
  check(win.x === 92 && win.y === 80 && win.width === 500 && win.height === 400, 'Escape cancels Size on both axes');
  check(bubbled === 0, 'System-menu keystrokes do not leak to file selection or terminal handlers');
  window.removeEventListener('keydown', onKey);
  menu(); key('x');
  const maxWidth = win.width;
  check(win.maximized, 'X maximizes');
  menu(); key('x');
  check(win.maximized && win.width === maxWidth, 'Maximize remains enabled and is idempotent');
  menu(); key('s'); key('ArrowRight'); key('ArrowRight');
  check(!win.maximized && win.width === 508, 'Size works from a maximized window');
  key('Escape');
  check(win.maximized && win.width === maxWidth, 'Cancel restores maximized state and bounds');
  menu(); key('n');
  check(win.el.classList.contains('minimized') && win.el.getBoundingClientRect().height < 40, 'N collapses to the titlebar');
  win.el.querySelector('.fm-titlebar').dispatchEvent(new MouseEvent('dblclick', { bubbles: true }));
  check(!win.el.classList.contains('minimized') && win.maximized && win.width === maxWidth, 'Double-click restores a collapsed titlebar without changing its previous size');
  win.toggleMinimize();
  menu(); key('r');
  check(!win.el.classList.contains('minimized') && win.maximized, 'Restore returns a minimized maximized window to its previous state');
  menu(); key('r');
  check(!win.maximized && win.width === 500, 'R restores normal bounds from maximized');
  win.toggleMinimize();
  menu(); key('s');
  check(!win.el.classList.contains('minimized'), 'Size reveals a collapsed viewport');
  key('Escape');
  check(win.el.classList.contains('minimized'), 'Cancel Size restores the collapsed state');
  menu(); key('r');
  menu(); key('m');
  window.dispatchEvent(new MouseEvent('mousemove', { clientX: 200, clientY: 150 }));
  window.dispatchEvent(new MouseEvent('mousemove', { clientX: 220, clientY: 160 }));
  check(win.x === 112 && win.y === 90, 'Move also follows mouse motion');
  window.dispatchEvent(new MouseEvent('mousedown', { button: 0, cancelable: true }));
  check(!WindowSystemMenu.operation && win.x === 112, 'Left click commits the mouse move');
  win.el.querySelector('.fm-titlebar').dispatchEvent(new MouseEvent('contextmenu', { clientX: 150, clientY: 110, bubbles: true, cancelable: true }));
  check(!!WindowSystemMenu.menu, 'Titlebar right-click opens the system menu');
  key('ArrowDown'); key('Enter'); key('Escape');
  check(!WindowSystemMenu.operation, 'Menu arrow navigation and Enter activate commands');
  nativeCommand('menu');
  check(!!WindowSystemMenu.menu, 'Main-process system-menu shortcut reaches the active internal window');
  nativeCommand('menu');
  check(!WindowSystemMenu.menu, 'Repeating the menu shortcut dismisses it');
  menu(); key('m'); key('ArrowRight');
  window.dispatchEvent(new Event('blur'));
  check(!WindowSystemMenu.operation && win.x === 112, 'Losing application focus cancels an unfinished move');
  menu(); key('c');
  check(!win.el.isConnected && manager.windows.length === 0, 'C closes only the targeted internal window');
  return results;
})()
